type Profile {
  id: String!
  firstName: String!
  lastName: String!
  birthday: String!
}

type Query {
  getProfile(id: Int!): [Profile]!
}

type Mutation {
  createProfile(firstName: String!, lastName: String!): Profile!
}
